name: Create release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    #if: ${{ github.ref_name == 'main' }}
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check-out
        # version 5.0.0: https://github.com/actions/checkout/commit/08c6903cd8c0fde910a37f88322edcfb5dd907a8
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          fetch-tags: true
          fetch-depth: 0    # fetch all tags and branches

#      - name: Debuggin'
#        run: |
#          git describe --tags
#          git describe --all
#          git describe
#          echo "${{ toJSON(github) }}"

      - name: Run tests before release
        run: ./run-tests.sh

      - name: Install build dependencies
        run: sudo apt install pandoc -y

      - name: Create release files
        run: ./build-packages.sh

      # The `gh release create` will fail if the tag has been released already
      - name: Publish release files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          export LATEST_TAG=$(git describe --abbrev=0)
          echo "Releasing '$LATEST_TAG'"
          gh release create "$LATEST_TAG" \
              --notes-from-tag \
              './dist/hello-world#hello-world - The standalone script' \
              './dist/LICENSE#LICENSE' \
              './dist/README.md#README.md' \
              './dist/manpage.md#manpage.md - Man page as markdown'

      - name: Publish docs on gh-pages
        env:
          USER_EMAIL: ${{ github.event.pusher.email }}
          USER_NAME: ${{ github.event.pusher.name }}
        run: |
          git config --local user.email "$USER_EMAIL"
          git config --local user.name "$USER_NAME"
          git fetch
          git checkout gh-pages || git checkout -b gh-pages
          git add -f docs/
          git commit -a -m "Update docs $(git describe)"
          git branch --set-upstream-to=origin/gh-pages
          git pull --rebase || echo "gh-pages branch not yet existing" 
          git push 
